GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "1231231",
    "author": "4214414",
    "url": "1242144.com",
    "likes": 9999,
    "userId": "5f158db0f6527925545b6bcf"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa28xMjMiLCJpZCI6IjVmMTY4ZGRjMTFjM2NkMmZmYzI0NDExOSIsImlhdCI6MTU5NTMxNjg2MH0.jLQNNuDe6ZvWibxVr1K8hX25AUH59tKlRpigwrih5uY

{
    "title": "testi-title",
    "author": "Miko1",
    "url": "testurl.com",
    "likes": 2,
    "userId": "5f168ddc11c3cd2ffc244119"
}

###
DELETE http://localhost:3003/api/blogs/5f169cf08d50a20e04edc896 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa28xMjMiLCJpZCI6IjVmMTY4ZGRjMTFjM2NkMmZmYzI0NDExOSIsImlhdCI6MTU5NTMxNjg2MH0.jLQNNuDe6ZvWibxVr1K8hX25AUH59tKlRpigwrih5uY


###

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "miko123",
    "name": "Miko",
    "password": "salasana"
}

###

POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "miko123",
    "password": "salasana"
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Sys Admin",
    "password": "hunter1"
}


###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "hunter1"
}