GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "1231231",
    "author": "4214414",
    "url": "1242144.com",
    "likes": 9999,
    "userId": "5f158db0f6527925545b6bcf"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Miko1",
    "url": "testurl.com",
    "likes": 2
}

###
DELETE http://localhost:3003/api/blogs/5f12be825714b919e027fcff HTTP/1.1


###

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "miko123",
    "name": "Miko",
    "password": "salasana"
}

###

POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "miko123",
    "password": "salasana"
}